# Generated by Django 5.2.4 on 2025-07-31 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='home_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.classroom'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='students',
            field=models.ManyToManyField(blank=True, to='student.student'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_department', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='major',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.major'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='subjectdetail',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.AddField(
            model_name='subjectdetail',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.subject'),
        ),
    ]
