# Generated by Django 5.2.4 on 2025-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='fKfjCxttO00hU7g5gE4Px9PQr4111iV6', editable=False, max_length=32, unique=True),
        ),
    ]
