# Generated by Django 5.2.4 on 2025-08-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='6P5HqwucuERdVvZTJvo8u1OYUpp5ubM9', editable=False, max_length=32, unique=True),
        ),
    ]
